framework:
  rate_limiter:
    jwt_login:
      policy: 'sliding_window'
      limit: 5
      interval: '1 minute'

    anonymous_api:
      policy: 'sliding_window'
      limit: 5
      interval: '1 minute'
